name: Release Package to NPM ðŸš€
on:
  release:
    types: [created]
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repository code ðŸ”Ž
        uses: actions/checkout@v2
      - name: Setup Node.js environment ðŸ’»
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
